### ISSUE TITLE
Minimized option not always working

### ISSUE THREAD

**Issue by robpvn** [Norkart/Leaflet-MiniMap#105]
Snipped from #104, att: @deeg @robertharm :

> Hi guys,
> 
> thanks a lot for adding minimized as option - unfortunately this does not seem to work on my site. I searched for any mistake I could have made, but couldnt find any, so your help would really be appreciated! See demo map at https://www.mapsmarker.com/dev/pro/2016/02/25/siteoriginyoast-issue/
> 
> I use the latest codebase and added the option minimized: true to the constructor:
> var miniMap_layermap_6 = new L.Control.MiniMap(osm_mapnik_minimap, {position: 'bottomright', width: 150, height: 150, collapsedWidth: 19, collapsedHeight: 19, zoomLevelOffset: -5, zoomAnimation: false, toggleDisplay: true, autoToggleDisplay: false, minimized: true}).addTo(layermap_6);
> Anyway this does not seem to have any effect. So I tried changing the default value on line 30 to "minimized: true," - didnt have any effects either.
> 
> It also seems that the minimap now needs 2 clicks before it is minimized - the first click does not have any effect.
> 
> Any help here would be appreciated!
> best,
> 
> Robert

From a quick glance it looks like setting this._minimized on line 86 intereferes with _setDisplay so that things get cancelled out.

**Comment by deeg** [comment]
I will try to take a look today or tomorrow.

**Comment by robertharm** [comment]
Hi @deeg 
did you already get the chance to take a look or can I help here somehow?
best,
Robert

**Comment by deeg** [comment]
@robertharm, sorry spaced on this and was on Holiday when you pinged.

I will look at this tomorrow.

**Comment by robpvn** [comment]
I had time to look at it today, so I think commit 2ca6a0869bd6b00bd4ee20f85318259f1d53a7ba fixes this. See th commit notes for why the minimap has to be briefly visible at startup.

**Comment by robpvn** [comment]
Made it version 3.3.0 - out now!

**Comment by robertharm** [comment]
thanks for the fix!
