### ISSUE TITLE
Click event on MiniMap is propagated to main map

### ISSUE THREAD

**Issue by pedroetb** [Norkart/Leaflet-MiniMap#114]
Main map is receiving the dom event for click. My workaround is stopping click propagation from minimap container (`miniMapInstance._miniMap._container`).

**Comment by robpvn** [comment]
Hmm, it shouldn't propagate, per https://github.com/Norkart/Leaflet-MiniMap/blob/master/src/Control.MiniMap.js#L59 . Can you make a jsfiddle or similar that reproduces this?

**Comment by pedroetb** [comment]
Right, here is stopping propagation for Leaflet event, but not for the dom element containing the minimap. If you use dom events, it propagates outside.

If it isn't clear enough, I'll make a jsfiddle or something later. Thanks!

**Comment by pedroetb** [comment]
Tested this again using current versions of **leaflet** (`v1.9.4`), **google-chrome** (`v129`) and **firefox** (`v131`).

The event propagation is gone, so not needing this workaround anymore:

```js
on(miniMapInstance._miniMap._container, 'click', function(evt) { evt.stopPropagation(); });
```
