### ISSUE TITLE
Leaflet-MiniMap plugin I had a problem using with Leaflet 1.0@rc

### ISSUE THREAD

**Issue by rafaelprad** [Norkart/Leaflet-MiniMap#115]
Dear Author.
When I tested your Leaflet-MiniMap plugin I had a problem using with Leaflet 1.0@rc that is locking at some position. Can you help us? I think that problem is on setView.

**Comment by robpvn** [comment]
I have tested it with 1.0 and think it in general should work, but if you've found something that's interesting! Could you please make a [JSFiddle](https://jsfiddle.net/) that reproduces the problem you're having, then I can look at it properly?

**Comment by rafaelprad** [comment]
Dear Roberto Nokart, I make a fiddle https://jsfiddle.net/rafaelprad/x6vuwzjv/, but I didnt have same problem. I will find this problem comparing my application again, I never think to use a Fiddle to try it, but when I will use in an external program I had problem with "pan" over a map. Close this issue and I will review again. Sorry for inconvenient.

**Comment by robpvn** [comment]
No problem, that's why making fiddles is helpful for both of us since it helps find out what the problem is! :+1:
