### ISSUE TITLE
Broken on Leaflet 1.0.1: Uncaught TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by gholol** [Norkart/Leaflet-MiniMap#119]

**Comment by robpvn** [comment]
Well, this sounds bad. We've been compatible with all of the 1.0 release candidates, so I thought we'd be free and clear. Will investigate!

**Comment by robpvn** [comment]
I've updated my examples to Leaflet 1.0.1, but I can't find any errormessages like this. Are you sure it occurred in the Minimap code? Could you provide a jsfiddle that reproduces the problem?

**Comment by gholol** [comment]
Hi @robpvn 

After further analysis, turns out it was an issue with another plugin :)
