### ISSUE TITLE
Click and center

### ISSUE THREAD

**Issue by atodd-geoplan** [Norkart/Leaflet-MiniMap#124]
Do you have any advice on how you would go about having the maps centre on mouse click on the minimap to the point under the click?

Is it possible to hook into the click events and center() function of the minimap?

Great plugin btw *it just works* with the Google Maps Mutant plugin :)

**Comment by robpvn** [comment]
Yes, I think that should work, because the main map position is updated when the minimap moveend event is fired. The minimap has a variable `_miniMap` which is a normal Leaflet map object with everything you need.
