### ISSUE TITLE
Leaflet 1.1.0 compatibility

### ISSUE THREAD

**Issue by robertharm** [Norkart/Leaflet-MiniMap#128]
"Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead."

Here is how this issue was solved for the GoogleMutant library: https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant/merge_requests/29

It would be great if this could also be fixed for Leaflet-MiniMap.

**Comment by TrySound** [comment]
Ping

**Comment by robertharm** [comment]
-> https://github.com/Norkart/Leaflet-MiniMap/pull/127#issuecomment-322763239

**Comment by robpvn** [comment]
I guess this is fixed with the merge of #127 ?

**Comment by robertharm** [comment]
yes, this is fixed with the merge of #127
