### ISSUE TITLE
How to prevent minimap moving outside defined MaxBounds?

### ISSUE THREAD

**Issue by COLABORATI** [Norkart/Leaflet-MiniMap#130]
I have a map that has bounds defined with `map.setmaxBounds` but the minimap scrolls outside that defined bounds into a grey area, what should not happen. 

How can I make the minimap respect the map defined bounds? I tried to set via `minimap.setBounds` but this will not work. 

Thank you very much for your attention!

**Comment by robpvn** [comment]
Wow, I guess thanking me for my attention was a bit premature! 

See https://github.com/Norkart/Leaflet-MiniMap#available-options ; you could pass the maxBounds as a mapOptions object to the minimap and that should probably work.
