### ISSUE TITLE
L.Control.MiniMap is not a constructor

### ISSUE THREAD

**Issue by Brnjrm** [Norkart/Leaflet-MiniMap#135]
Hi, 
I try your plug-in for the first time on leaflet. I follow the examples in their simplest way before puting more options.
In the browser (with F12), there's an error message saying L.Control.MiniMap is not a constructor
After reading the dozens of posts in the issue tab, I realise there's no info about this issue, which means the problem is not relying on the pluggin but on the general code I wrote, or the problem is new.

Coud you have a look to the jsFiddle here : https://jsfiddle.net/BrunJerome/ek4g3u8k/2/

Thanks for your ideas to allow me to clean the code and to make the plug-in function.

Jérôme

**Comment by Brnjrm** [comment]
I've found the solution: there was an error in the html.
Thanks for your plug in

**Comment by robpvn** [comment]
Hi, sorry for responding slowly, but I'm glad you solved the problem! Thank you for your kind words about the plugin. 👍

**Comment by johnfrades** [comment]
> I've found the solution: there was an error in the html. Thanks for your plug in

whats the error in HTML?
