### ISSUE TITLE
Deprecated include of L.Mixin.Events

### ISSUE THREAD

**Issue by ventralnet** [Norkart/Leaflet-MiniMap#138]
https://github.com/Leaflet/Leaflet/pull/5365

The use of including L.Mixin.Events and you are to use L.Evented instead.  Leaflet warns on the javascript console with the deprecation message saying L.Mixin.Events including will be removed in future releases

leaflet: 1.3.1
leaflet-minimap: 3.6.1

**Comment by robpvn** [comment]
Yes, this needs to be fixed before future Leaflet releases. Sorry about the late answer!
