### ISSUE TITLE
Fit the zoom to map size on minimap

### ISSUE THREAD

**Issue by tpatikirikorala** [Norkart/Leaflet-MiniMap#140]
We load a map of a building using leaflet. However when we use minimap it is hard to calculate the zoom level. Default viewport has large white space around the map view port, which is entirely covered by aimingRect.  i.e around aimingRect there is large whitespace.

We use  deepzoom layer as tileLayer to be added to MiniMap. 
1) Any idea how to calculate the zoom level, so that default view port fills up control without large white space
2) is there away to set scrollWheelZoom to false, so that we can disable zooming.

**Comment by robpvn** [comment]
Hi, sorry about being so late to answer.  I have no experience with deepzoom layer, but I guess it's probably related to CRSes being different, like with https://github.com/Norkart/Leaflet-MiniMap/issues/132 .

Like it says in the readme, there is an option to set `zoomLevelFixed` to whatever zoom you want, which will disable zooming.
