### ISSUE TITLE
Collapsed minimap by default?

### ISSUE THREAD

**Issue by seyfro** [Norkart/Leaflet-MiniMap#16]
Hi,

thanks for your great plugin - I plan to add this to one of the next releases of my plugin mapsmarker.com (plus an integrated settings panel to set the available options).
Just one question which I couldnt figure out quickly: is it possible to launch the minimap minimized? (as google does it?)

I tried changing the following function to true, but with no success:
_addToggleButton: function () {
        this._toggleDisplayButton = this.options.toggleDisplay ? this._createButton(
                '', 'Hide', 'leaflet-control-minimap-toggle-display',  this._container, this._toggleDisplay,  this) : undefined;
        this._minimized = true;
    },

can you please help here?
Thx,

Robert

**Comment by buckyj** [comment]
Thank you very much for your solution.
