### ISSUE TITLE
How to make a clickable and interactive task list?

### ISSUE THREAD

**Issue by audreyspency** [Norkart/Leaflet-MiniMap#161]
Hi, I am currently managing a point project in my Remarkable, what I am doing now is the following. I put a list in the template of boxes to mark completed tasks and I write in each line each important step to achieve, the thing is that this time that step is divided into 10 more steps that also have boxes to mark as completed, my methodology is in each step to finish each small part of the page and when I complete it I go to the next step. Now that remarkable  2 has linkable sentences I would like to know if someone can pass me a template of this style where clicking on one of the tasks takes me to another page with all the tasks in which it is divided, it would be cleaner and more simplified for me to work.
<a href="https://kodi.software/">Kodi</a> <a href="https://nox.uno/">nox</a>

**Comment by kjartab** [comment]
Not sure how this relates to Leaflet-MiniMap?

**Comment by atlefren** [comment]
From your description I am struggeling to see how your problem relates to the leaflet minimap plugin at all. Could you please elaborate?
