### ISSUE TITLE
L_PREFER_CANVAS = true breaks the map

### ISSUE THREAD

**Issue by DrYSG** [Norkart/Leaflet-MiniMap#35]
Rob,

Thank you for being patient. I have continued to work on my CodePen demo to get the the heart of the problem. Why? Certainly not to bother you, since I think you have done a great service creating this plug-in.

But something did not ring true, when about the suggesting that issue #33 was due to delayed tile response (jquery promise) from the IndexedDB. Why? well Leaflet is designed for all tiles to be returned async from web services. So the mere fact that tiles are coming back async should not effect things such as bounding boxes, zoom, etc. (this is just about splatting bits on the screen, a purely visual effect).

So I created a more minimal demo, CRS3857, with TileLayers from CloudMade, and I am seeing the same errors:

http://codepen.io/DrYSG/pen/ICzro

I am really shooting in the dark now as to what the problem is:

1. something in leaflet 0.7?
2. something else?

There are no other controls, that I can see (other than the zoom), so what do you think is causing this. Given that the symptom is the same as with Functional and IDB, I am thinking there is something more basic at fault (and I don't rule out how I am setting up the MiniMap).

**Comment by robpvn** [comment]
This is an old issue, but we're still at Leaflet 7.x. 1.0 should be coming real soon, though, so fingers crossed!

**Comment by robpvn** [comment]
Closing this now because Leaflet 1.0 is in a beta release, so things should be good, I hope.

**Comment by bozdoz** [comment]
I realize this bug is 3 years old, but it's something that has kept me from using this plugin for 3 years.  Thought I would post my recent solution, with Leaflet 0.7.7:

Overwrite `_requestUpdate` after initializing `_aimingRect/_shadowRect` :

```
if (window.L_PREFER_CANVAS) {
	// rewrite _request
	this._aimingRect._requestUpdate = this._shadowRect._requestUpdate = function () {
		if (this._map && !L.Path._updateRequest) {
			L.Path._updateRequest = L.Util.requestAnimFrame(function () {
				L.Path._updateRequest = null;
				
				// wipe canvas
				this._map._updateCanvasViewport();

				this._updatePath();
			}, this);
		}
	};
}
```

**Comment by robpvn** [comment]
Useful in case someone can't use 1.0 (or 1.0 didn't fix it after all), thanks!
