### ISSUE TITLE
how to call invalidateSize() on minimap?

### ISSUE THREAD

**Issue by robertharm** [Norkart/Leaflet-MiniMap#39]
A user of my plugin www.mapsmarker.com uses leaflet maps in woocommerce tabs, which forced me to add a workaround to invalidateSize() of the map on tab change and initial load.

See http://www.nebbiolowijn.nl/winkel/product/salice-salentino-albarossa/ for an example: the map shows correclty, but the minimap would also
neet to get to be reloaded by invalidateSize(). 

Unfortunately I didnt find out how to do so with the minimap plugin - I tried adding the following private method, but that didnt work:

_invalidateSizeMinimap: function (map) {
        this._miniMap.invalidateSize();
        return this;
    },

Can anyone please help here and tell me how this can be achieved?

**Comment by robpvn** [comment]
Housekeeping: This issue is way stale and with Leaflet 1.0 coming out it might not even apply anymore. So I'll close this and if anybody experiences this issue in the future, a new bug can be opened.
