### ISSUE TITLE
Add missing bower.json.

### ISSUE THREAD

**Issue by timgluz** [Norkart/Leaflet-MiniMap#50]
#### Hey, maintainer(s) of Norkart/Leaflet-MiniMap!

We at [VersionEye](https://www.versioneye.com/signup?promo_code=BOWER) are working hard to keep up the quality of the bower's registry.

We just finished our initial analysis of the quality of the Bower.io registry:

**7530** - registered packages, *224* of them doesnt exists anymore;

We analysed **7306**  existing packages and  **1070** of them don't have bower.json on the master branch ( _that's where a Bower client pulls a data_ ).

Sadly, your library `Norkart/Leaflet-MiniMap` is one of them.

Can you spare **15** minutes to help us to make Bower better?

Just add a new file `bower.json` and  change attributes.

```
{
  "name": "Norkart/Leaflet-MiniMap",
  "version": "1.0.0",
  "main": "path/to/main.css",
  "description": "please add it",
  "license": "Eclipse",
  "ignore": [
    ".jshintrc",
    "**/*.txt"
  ],
  "dependencies": {
    "<dependency_name>": "<semantic_version>",
    "<dependency_name>": "<Local_folder>",
    "<dependency_name>": "<package>"
  },
  "devDependencies": {
    "<test-framework-name>": "<version>"
  }
}

```

Read more about bower.json [on the official spefication](http://bower.io/#defining-a-package) and nodejs [semver](https://github.com/isaacs/node-semver#ranges) library has great examples of proper versioning.

**NB!** Please _validate_ your bower.json with _jsonlint_ before commiting your updates.

Thank you!

Timo,
twitter: @versioneye
email: timo@versioneye.com
[VersionEye](https://www.versioneye.com/signup?promo_code=BOWER) - no more legacy software!

**Comment by robpvn** [comment]
I see from the [0.7.3](https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md#073-may-23-2014) changelog for Leaflet that they've included bower support a while now. Might be time to revisit this issue now.

**Comment by reiz** [comment]
I just checked out the changes, but there is still no bower.json file in the root directory. We track the project anyway, but as long there is now bower.json file we have no information about dependencies, licenses, description, authors and so on.

**Comment by Xennis** [comment]
+1 for a bower.json

**Comment by deeg** [comment]
+1 for bower support!

**Comment by deeg** [comment]
Is there anything we can do to help with bower support?

**Comment by robpvn** [comment]
I've added a bower.json, so I think things should be available now soon. (Someone had already registered this repo in the bower registry with the correct git address, so I suppose things should be showing up correctly now that the bower.json is in place.)

@deeg: If you want to help, try using bower to install `leaflet-minimap` and see if it all works properly. IF something is wrong with the bower.json, pull requests are welcome.

**Comment by reiz** [comment]
Cool! Many THX for the bower.json :-)

**Comment by deeg** [comment]
It is working now, thanks. I do suggest adding to the readme about how to run the command to install it, since it is all lower case while this repo as caps.

Also I think it is pretty good practice to have a version number in your bower.json file if you want to add one.

**Comment by robpvn** [comment]
[The spec](https://github.com/bower/spec/blob/master/json.md) actually says that a version number is deprecated and ignored, so I'm happy to not have to mess about with updating that manually when I `npm version major/minor/patch`.

I can put somtehing in the readme!

**Comment by deeg** [comment]
Ah, thanks for letting me know!
