### ISSUE TITLE
NPM registry

### ISSUE THREAD

**Issue by DrYSG** [Norkart/Leaflet-MiniMap#65]
How about adding this package to the NPM registry? You already have a package.json, so it should be simple.

probably just "npm publish"

here is all the steps from scratch:

http://decodize.com/javascript/build-nodejs-npm-installation-package-scratch/

**Comment by robpvn** [comment]
Yeah OK, that was super easy. I had to `npm adduser` first but then it was just npm publish`. We're now available on NPM! :shipit:
