### ISSUE TITLE
Angular leaflet directive integration

### ISSUE THREAD

**Issue by nurseymybush** [Norkart/Leaflet-MiniMap#82]
Hello,
I was wondering how I would go about using the minimap plugin for leaflet with angular leaflet? So far i have but it doesn't work : 
controls: {
            MiniMap: {
                layer: 'osm2'
            }
}
Thanks very much

**Comment by robpvn** [comment]
I guess the angular leaflet directive needs to implement support for the MiniMap? I don't really know anything about it, sorry. Hopefulley you'll get more useful help on the issue you filed there. (https://github.com/tombatossals/angular-leaflet-directive/issues/797)

**Comment by nurseymybush** [comment]
Ok thank you very much for your help
