### ISSUE TITLE
Does not support a zoomLevelFixed of 0

### ISSUE THREAD

**Issue by ventralnet** [Norkart/Leaflet-MiniMap#86]
Currently if you want a fixed zoom level of 0 this will not work.  Looks like the code is using options.zoomLevelFixed for falsey truthy comparisons such as on line 240 in the _decideZoom function

    if (!this.options.zoomLevelFixed) {

With a zoomLevelFixed of 0 this would evaluate to false and ignore your zoomLevelFixed setting.

**Comment by robpvn** [comment]
Good point, definitely an oversight of an edge case.

**Comment by ventralnet** [comment]
I can submit a pull request, but it won't be for another 10 or so hours until I get home

**Comment by robpvn** [comment]
:+1:
