### ISSUE TITLE
Fixed minimap

### ISSUE THREAD

**Issue by geoffreyjoseph** [Norkart/Leaflet-MiniMap#90]
Is there anyway to keep the minimap in a fixed position and just move the selection box? I am working on a statewide map in which the user can search and be zoomed in to the result. I would like to have the minimap stay fixed on a overview of the state and the highlight box showing the area of the state being viewed to move over the selected area. Is this possible?

**Comment by robpvn** [comment]
If you set the `zoomLevelFixed` option to true along with the zoom level you need to show your whole state, that should work. If you additionally set the `maxBounds` option on the main map so the user can't navigate out of your desired area it should be all you need. :ok_hand:
