### ISSUE TITLE
Fix minimap on point / bounds

### ISSUE THREAD

**Issue by mnquintana** [Norkart/Leaflet-MiniMap#94]
It would be really useful to be able to fix the MiniMap (ie. prevent it from zooming / panning along with the main map) by passing it a point (a `LatLng` object or an array) or bounds. Use case here is to have a minimap be a fixed view on a particular point in the map, no matter the state of the main map. Thanks!

**Comment by mnquintana** [comment]
This is sort of related to https://github.com/Norkart/Leaflet-MiniMap/issues/77, but would be adding additional config options.

**Comment by robpvn** [comment]
This also seems quite doable, all we need is to add it as options that we pass through to the underlying Map object. Looking at http://leafletjs.com/reference.html#map-options it seems that only the bounds option is supported out of the box, so we'll stick to that.

**Comment by mnquintana** [comment]
Sweet, good to hear! I'll try to get a PR together for this soon.
